# This is a basic workflow to help you get started with Actions

name: Slack

# Controls when the workflow will run
on:
  
  pull_request:
    branches: [ main ]



jobs: 
  slack:
    runs-on: ubuntu-latest

  
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
            args: '{\"channel\":\"C03GQ5PNACS\",\"text\":\"Hello world\"}'
